In [1]:
import  numpy as np

### Learining array in numpy

In [2]:
array_1d = np.array([1, 2, 3, 4, 5])
array_1d

array([1, 2, 3, 4, 5])

### Two dimensionl; array

In [3]:
array_2d = np.array([[2,3,4,5], [2,3,4,5],[3,9,6,6]])
print(array_2d)


[[2 3 4 5]
 [2 3 4 5]
 [3 9 6 6]]


### Three dimensional array

In [4]:
array_3d = np.array([[[2,3,4],[4,5,6],[2,3,4]]])
print(array_3d)

[[[2 3 4]
  [4 5 6]
  [2 3 4]]]


In [5]:
array_2d.ndim

2

### One  dimension array

### Linspace method

In [6]:
array_1d = np.linspace(1,10,5)
array_1d

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### to check the dimension of th array

In [7]:
array_1d.ndim

1

In [8]:
d=[1,2,3,4]

### shape of array

In [9]:
d = [1,2,3,4]

In [10]:
array_1d.shape

(5,)

In [11]:
array_2d.shape

(3, 4)

In [12]:
array_3d.shape

(1, 3, 3)

### size of the array


In [13]:
array_1d.size

5

In [14]:
array_2d.size

12

### Arrange function in numpy array

In [15]:
array1 = np.arange(1,101)
array1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [16]:
odd_array = np.arange(1,101,2)
odd_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

### Arithmetic operation in numpy

In [17]:
list1 =[1,2,3,4]
list2 =[2,3,4,5]
print(list1 + list2)

[1, 2, 3, 4, 2, 3, 4, 5]


In [18]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr1 + arr2)

[ 6  8 10 12]


In [19]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr1 * arr2)

[ 5 12 21 32]


In [20]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr1 / arr2)

[0.2        0.33333333 0.42857143 0.5       ]


In [21]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr1 - arr2)

[-4 -4 -4 -4]


In [22]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr3 = np.array([4,5,6,4])
print(arr1 * arr2 - arr3)

[ 1  7 15 28]


In [23]:
arr4 = np.array([[1,2,3],
                 [2,3,4],
                 [3,4,5]])
arr5 = np.array([[4,5,6],
                 [5,6,7],
                 [6,7,8]])
arr4 * arr5

array([[ 4, 10, 18],
       [10, 18, 28],
       [18, 28, 40]])

### for matrix multiplication

In [24]:
### @ for multiplication

### Concatenation in numpy

In [25]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
arr3 = np.concatenated((arr1,arr2))
arr3


AttributeError: module 'numpy' has no attribute 'concatenated'

### for two dimension array

In [ ]:
arr2d1 = np.array([[1,2,3],
                   [2,3,4],
                                                     ### axis 1 is right side    and axis0 is down side 
                   [5,6,7]])
arr2d2 = np.array([[5,6,7],
                   [6,7,8],
                   [8,9,6]])
np.concatenate((arr2d1, arr2d2), axis=0)



array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7],
       [5, 6, 7],
       [6, 7, 8],
       [8, 9, 6]])

In [ ]:
arr2d1 = np.array([[1,2,3],
                   [2,3,4],
                                                     ### axis 1 is right side    and axis0 is down side 
                   [5,6,7]])
arr2d2 = np.array([[5,6,7],
                   [6,7,8],
                   [8,9,6]])
np.concatenate((arr2d1, arr2d2), axis=1)

array([[1, 2, 3, 5, 6, 7],
       [2, 3, 4, 6, 7, 8],
       [5, 6, 7, 8, 9, 6]])

### hstack and vstack

In [ ]:
arr1 = np.array([[6,7,8,9],
                 [4,5,6,7]])
arr2 = np.array([[2,3,4,5]])
np.vstack((arr1, arr2))

array([[6, 7, 8, 9],
       [4, 5, 6, 7],
       [2, 3, 4, 5]])

In [ ]:
np.vstack((arr1,arr2))

array([[6, 7, 8, 9],
       [4, 5, 6, 7],
       [2, 3, 4, 5]])

### slicing in numpy array

In [ ]:
array1 = np.arange(1,11)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
array2 = array1[3:7]
array2

array([4, 5, 6, 7])

### for two dimensional array

In [ ]:
array2 = np.array([[4,5,6,7],
                   [6,7,8,9],
                   [1,2,3,4]])
array2.shape


(3, 4)

In [ ]:
array2.ndim

2

In [ ]:
array2[1,1]

np.int64(7)

In [ ]:
array2[1:3,1:3]

array([[7, 8],
       [2, 3]])

In [ ]:
array2[0:,1:3]

array([[5, 6],
       [7, 8],
       [2, 3]])

In [ ]:
array2.reshape(2,6)     ## only if size and number are same

array([[4, 5, 6, 7, 6, 7],
       [8, 9, 1, 2, 3, 4]])

In [ ]:
array2.shape


(3, 4)

In [ ]:
array2.reshape(12)

array([4, 5, 6, 7, 6, 7, 8, 9, 1, 2, 3, 4])

In [ ]:
array2.reshape(2,2,3)

array([[[4, 5, 6],
        [7, 6, 7]],

       [[8, 9, 1],
        [2, 3, 4]]])

In [ ]:
array = np.arange(1,101)
array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
array.reshape(20,5)

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

### spliting in numpy


In [ ]:
array1 = np.random.randint(100, 500, size = (9,6))
array1

array([[252, 348, 344, 466, 443, 184],
       [267, 109, 372, 359, 280, 313],
       [442, 470, 218, 336, 463, 469],
       [409, 334, 401, 290, 253, 404],
       [346, 356, 293, 383, 490, 223],
       [190, 469, 459, 250, 196, 220],
       [274, 237, 278, 108, 418, 104],
       [127, 376, 472, 369, 328, 211],
       [437, 417, 275, 256, 104, 131]], dtype=int32)

In [ ]:
array1_1, array2_2, array3_3 = np.split(array1, 3, axis=0)
array1_1

array([[252, 348, 344, 466, 443, 184],
       [267, 109, 372, 359, 280, 313],
       [442, 470, 218, 336, 463, 469]], dtype=int32)

In [ ]:
array2_2

array([[407, 285, 453, 276, 419, 253],
       [238, 458, 347, 489, 100, 247],
       [136, 267, 495, 414, 314, 337],
       [347, 428, 254, 137, 260, 274],
       [122, 493, 463, 465, 310, 177]], dtype=int32)

In [ ]:
 array3_3

array([[274, 237, 278, 108, 418, 104],
       [127, 376, 472, 369, 328, 211],
       [437, 417, 275, 256, 104, 131]], dtype=int32)

### coloum wise spliting 

In [ ]:
array1 = np.random.randint(100, 500, size = (10,6))

In [ ]:
array1_1,array1_2= np.split(array1,2, axis=1)
array1_1

IndexError: tuple index out of range

In [ ]:
array1_2

array([[268, 164, 103],
       [341, 148, 202],
       [154, 275, 286],
       [218, 320, 191],
       [388, 156, 168],
       [398, 313, 466],
       [240, 378, 460],
       [253, 245, 123],
       [309, 189, 431],
       [217, 137, 292]], dtype=int32)

In [ ]:
array1_1, array1_2 = np.split(array1, [5], axis=1)
array1_1

array([[409, 170, 286, 268, 164],
       [422, 391, 490, 341, 148],
       [355, 429, 262, 154, 275],
       [301, 480, 224, 218, 320],
       [146, 179, 260, 388, 156],
       [472, 367, 197, 398, 313],
       [257, 353, 384, 240, 378],
       [149, 291, 447, 253, 245],
       [351, 332, 497, 309, 189],
       [395, 119, 172, 217, 137]], dtype=int32)

In [ ]:
array1_1, array1_2,array1_3= np.split(array1, [3,5], axis=1)
array1_2

array([[288, 439],
       [485, 173],
       [177, 305],
       [247, 141],
       [251, 274],
       [418, 458],
       [204, 400],
       [145, 475],
       [422, 345],
       [293, 209]], dtype=int32)

### load the dataset into numpy arary

In [ ]:
iris_array = np.genfromtxt(r"C:\Users\lenovo\Desktop\Numpy\iriss.txt", delimiter=',', dtype=str)

In [ ]:
iris_array

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1

In [ ]:
iris1_1,iris1_2 = np.split(iris_array, [4],axis=1)
iris1_1

array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2'],
       ['5.4', '3.9', '1.7', '0.4'],
       ['4.6', '3.4', '1.4', '0.3'],
       ['5.0', '3.4', '1.5', '0.2'],
       ['4.4', '2.9', '1.4', '0.2'],
       ['4.9', '3.1', '1.5', '0.1'],
       ['5.4', '3.7', '1.5', '0.2'],
       ['4.8', '3.4', '1.6', '0.2'],
       ['4.8', '3.0', '1.4', '0.1'],
       ['4.3', '3.0', '1.1', '0.1'],
       ['5.8', '4.0', '1.2', '0.2'],
       ['5.7', '4.4', '1.5', '0.4'],
       ['5.4', '3.9', '1.3', '0.4'],
       ['5.1', '3.5', '1.4', '0.3'],
       ['5.7', '3.8', '1.7', '0.3'],
       ['5.1', '3.8', '1.5', '0.3'],
       ['5.4', '3.4', '1.7', '0.2'],
       ['5.1', '3.7', '1.5', '0.4'],
       ['4.6', '3.6', '1.0', '0.2'],
       ['5.1', '3.3', '1.7', '0.5'],
       ['4.8', '3.4', '1.9', '0.2'],
       ['5.0', '3.0', '1.6', '0.2'],
       ['5.0', '3.4', '1.6', '0.4'],
 

In [ ]:
iris1_2

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-se

In [ ]:
iris1_2[:5]

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa']], dtype='<U15')

In [ ]:
iris1_1[:5, :2]

array([['5.1', '3.5'],
       ['4.9', '3.0'],
       ['4.7', '3.2'],
       ['4.6', '3.1'],
       ['5.0', '3.6']], dtype='<U15')

In [ ]:
iris1_1.dtype

dtype('float64')

In [ ]:
iris1_1 = iris1_1.astype(float)

#### mean

In [ ]:
array1 = np.array([12,13,16,10])
mean = np.mean(array1)
mean

np.float64(12.75)

In [ ]:
median = np.median([12,14,15,18,10])
median = np.median(median)
median

np.float64(14.0)

In [ ]:
standard_deviation = np.std(array1)
standard_deviation

np.float64(2.165063509461097)

In [ ]:
array_2 = np.random.randint(15.25, size = (6,4))
array_2

array([[10,  1,  9,  8],
       [ 2,  0,  0,  8],
       [ 5, 11,  2,  6],
       [ 3, 11,  6, 13],
       [13,  2,  9, 12],
       [ 0,  5,  2,  9]], dtype=int32)

In [ ]:
array_2_mean = np.mean(array_2, axis=0)
array_2_mean

array([5.5       , 5.        , 4.66666667, 9.33333333])

In [ ]:
array_2_mean = np.mean(array_2, axis=1)
array_2_mean

array([7.  , 2.5 , 6.  , 8.25, 9.  , 4.  ])

In [ ]:
sepal_mean = np.mean(iris1_1, axis=0)
sepal_mean

array([5.84333333, 3.054     , 3.75866667, 1.19866667])

In [ ]:
sepal_mean = np.mean(iris1_1, axis=1)
sepal_mean

array([2.55 , 2.375, 2.35 , 2.35 , 2.55 , 2.85 , 2.425, 2.525, 2.225,
       2.4  , 2.7  , 2.5  , 2.325, 2.125, 2.8  , 3.   , 2.75 , 2.575,
       2.875, 2.675, 2.675, 2.675, 2.35 , 2.65 , 2.575, 2.45 , 2.6  ,
       2.6  , 2.55 , 2.425, 2.425, 2.675, 2.725, 2.825, 2.4  , 2.4  ,
       2.625, 2.4  , 2.225, 2.55 , 2.525, 2.1  , 2.275, 2.675, 2.8  ,
       2.375, 2.675, 2.35 , 2.675, 2.475, 4.075, 3.9  , 4.1  , 3.275,
       3.85 , 3.575, 3.975, 2.9  , 3.85 , 3.3  , 2.875, 3.65 , 3.3  ,
       3.775, 3.35 , 3.9  , 3.65 , 3.4  , 3.6  , 3.275, 3.925, 3.55 ,
       3.8  , 3.7  , 3.725, 3.85 , 3.95 , 4.1  , 3.725, 3.2  , 3.2  ,
       3.15 , 3.4  , 3.85 , 3.6  , 3.875, 4.   , 3.575, 3.5  , 3.325,
       3.425, 3.775, 3.4  , 2.9  , 3.45 , 3.525, 3.525, 3.675, 2.925,
       3.475, 4.525, 3.875, 4.525, 4.15 , 4.375, 4.825, 3.4  , 4.575,
       4.2  , 4.85 , 4.2  , 4.075, 4.35 , 3.8  , 4.025, 4.3  , 4.2  ,
       5.1  , 4.875, 3.675, 4.525, 3.825, 4.8  , 3.925, 4.45 , 4.55 ,
       3.9  , 3.95 ,